config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :articles

#  	get "/articles"
 # 	post "/articles"
  #	delete "/articles"
  #	get "/articles/:id"
  #	get "/articles/:new"
  #	get "/articles/:id/edit"
  #	patch "/articles/:id"
  #	put "/articles/:id"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: {minimum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_user!, except: [:show,:index]
	before_action :set_article, except: [:index,:new]
	
	#GET /articles
	def index
		@articles = Article.all
	end

	#GET /articles/:id
	def show		
	end

	#GET /articles/new
	def new
		@article = Article.new
	end

	def edit	
		
	end

	#POST /article
	def create
		@article = current_user.articles.new(articles_params)
		if @article.save
			redirect_to @article
		else
			render :new		
		end
	end
	def destroy
		
		@article.destroy #elimina objeto de la BD
		redirect_to articles_path
	end

	def update			
		if @article.update(articles_params)
			redirect_to @article
		else
			render :edit
		end
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def validate_user
		redirect_to new_user_session_path, notice: "Necesitas Iniciar Sesion"
	end

	def articles_params
		params.require(:article).permit(:title,:body)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f|%>
		<% @article.errors.full_messages.each do |message| %>
			<div class = "error field">
				* <%=message%>
			</div>
		<%end%>

		<div class="field">
			<%= f.text_field :title, placeholder: "Titulo",class:"form-control"%>
		</div>

		<div class="field">
			<%= f.text_area :body, placeholder: "Escribe aqui el articulo", style: "height:250px;",class:"form-control" %>
		</div>
		<div class="field">
			<%= f.submit "Guardar",class:"btn"%>
		</div>

<%end%>

app/views/articles/edit.html.erb
<div class="container-body">

  <div class="row middle-xs center-xs">
    <div class="col-xs-8 aling-left">

	<h1 class="field">Editar Articulo</h1>

	<%= render "form" %>

</div>

</div>
</div>

app/views/articles/index.html.erb
<div class="container-body">
	<% @articles.each do |article| %>

	<h1><%=link_to article.title, article %></h1>
<div>
	<p>
		<%=article.body %> - <%= link_to "Eliminar",article, method: :delete, class:"elim"%>
	</p>
	<% end %>
</div>
	
</div>

app/views/articles/new.html.erb
<div class="container-body">

  <div class="row middle-xs center-xs">
    <div class="col-xs-8 aling-left">
	
	<h1 class="field">Crear Articulo</h1>

	<%= render "form" %>

</div>
</div>
  
</div>

app/views/articles/show.html.erb
<div class="container-body">
	<h1><%=@article.title %></h1>
<div>
	<%unless @article.user.nil?%>
	<p>
		Escrito por <%= @article.user.email %>
	</p>
	<%end%>
	<div>
		<%=@article.body %> - <%= link_to "Editar", edit_article_path(@article) %>		
	</div>	
	
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   

    <%=render "partials/navigation" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header>
      <div class="logo-menu">
        <div class="container">
          <div class="row between-xs middle-xs center-xs">
            <div class="logo col-md-3 col-xs-12">
              <h1 class="no-margin" id="logo">Blog Logo</h1>
            </div>
            <nav class="col-md-5 col-xs-12">
              <ul class="no-list">                 
                <li class="enl">
                  <%= link_to "Inicio", root_path %>          
                </li>
                <li class="">
                  <%= link_to "Programacion", "https://google.com.mx" %>
                </li>
                <li class="">
                  Diseño
                </li>
                <li class="">
                  Tecnologia
                </li>               
              </ul>
            </nav>

            <%if user_signed_in?%>
              <div class = "col-md-3 col-xs-12">                  
                  <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>             
              </div>            
            <%else%>
              <div class = "col-md-3 col-xs-12">
                  <%= link_to "Iniciar Sesion", new_user_session_path %>                  
                 - <%= link_to "Crear Cuenta", new_user_registration_path %>
              </div>              
          </div>
          <%end%>
          
        </div>

      </div>
    </header>

app/views/welcome/index.html.erb
<%if user_signed_in?%>
	<h1>BIENVENIDO <%= current_user.email%></h1>
                  
 
          <%end%>